### ISSUE TITLE
Login method broke

### ISSUE THREAD

**Issue by chewvader** [saltstack/pepper#116]
Looks like the login method changed in the 0.5.3 update, and broke a number scripts for me.
https://github.com/saltstack/pepper/commit/5508c6c9a8f3ceaf5a3fbbe133b748c47aa199e6?diff=split

`returned exception: login() takes exactly 1 argument (4 given)`

The docstring still lists the old login method parameters:
https://github.com/saltstack/pepper/blob/develop/pepper/libpepper.py#L38

For a patch version number update, can we make this change in a backwards compatible fashion?

**Comment by gtmanfred** [comment]
Whoops, yeah that needs to be fixed.

**Comment by gtmanfred** [comment]
https://github.com/saltstack/pepper/releases/tag/0.5.4

Fixed, thanks for letting us know!

**Comment by djaara** [comment]
previous version 0.5.2 worked for us, 0.5.4 throws KeyError:

```
2018-03-02 16:00:04,831|P=1|T=140530947025704|ERROR  |salt_executor             |<module>    |'username'
Traceback (most recent call last):
  File "/salt_executor.py", line 44, in <module>
    start_executor(SALT_API_TARGET)
  File "salt_executor.py", line 28, in start_executor
    pepper.login(SALT_API_USERNAME, SALT_API_PASSWORD, 'pam')
  File "/usr/local/lib/python3.5/site-packages/pepper/libpepper.py", line 455, in login
    'eauth'
  File "/usr/local/lib/python3.5/site-packages/pepper/libpepper.py", line 456, in <genexpr>
    ) if locals()[key] is not None
KeyError: 'username'
```
