### ISSUE TITLE
 if locals()[key] is not None KeyError: 'username'`

### ISSUE THREAD

**Issue by vangourd** [saltstack/pepper#120]
`$ pepper '*' test.ping -a pam -v -v -v -v`

**Results in**
```
'username'
Uncaught Pepper error (increase verbosity for the full traceback).Uncaught traceback:
Traceback (most recent call last):
  File "/home/vangourd/.local/share/virtualenvs/saltReport-ocHoHA6r/bin/pepper", line 26, in <module>
    for exit_code, result in cli.run():
  File "/home/vangourd/.local/share/virtualenvs/saltReport-ocHoHA6r/local/lib/python2.7/site-packages/pepper/cli.py", line 521, in run
    self.login(api)
  File "/home/vangourd/.local/share/virtualenvs/saltReport-ocHoHA6r/local/lib/python2.7/site-packages/pepper/cli.py", line 489, in login    auth = login(**self.parse_login())
  File "/home/vangourd/.local/share/virtualenvs/saltReport-ocHoHA6r/local/lib/python2.7/site-packages/pepper/libpepper.py", line 455, in login    'eauth'
  File "/home/vangourd/.local/share/virtualenvs/saltReport-ocHoHA6r/local/lib/python2.7/site-packages/pepper/libpepper.py", line 456, in <genexpr>
    ) if locals()[key] is not None
KeyError: 'username'
DEBUG 2018-03-01 17:01:34,051 pepper: Uncaught traceback:
Traceback (most recent call last):
  File "/home/vangourd/.local/share/virtualenvs/saltReport-ocHoHA6r/bin/pepper", line 26, in <module>
    for exit_code, result in cli.run():
  File "/home/vangourd/.local/share/virtualenvs/saltReport-ocHoHA6r/local/lib/python2.7/site-packages/pepper/cli.py", line 521, in run
    self.login(api)
  File "/home/vangourd/.local/share/virtualenvs/saltReport-ocHoHA6r/local/lib/python2.7/site-packages/pepper/cli.py", line 489, in login
    auth = login(**self.parse_login())
  File "/home/vangourd/.local/share/virtualenvs/saltReport-ocHoHA6r/local/lib/python2.7/site-packages/pepper/libpepper.py", line 455, in login
    'eauth'
  File "/home/vangourd/.local/share/virtualenvs/saltReport-ocHoHA6r/local/lib/python2.7/site-packages/pepper/libpepper.py", line 456, in <genexpr>
    ) if locals()[key] is not None
KeyError: 'username'`
```
My `~/.pepperrc` is
```
[main]
SALTAPI_URL=https://salt.contoso.com:8000
SALTAPI_USER=admin
SALTAPI_EAUTH=pam
```

The error appears to be that when pepper calls the login function its not actually getting the username kwarg.

**Comment by siretty** [comment]
I encountered the same error, the following patch (based on tags/0.5.4) fixes the issue:

````patch
diff --git a/pepper/libpepper.py b/pepper/libpepper.py
index 236d359..589e05a 100644
--- a/pepper/libpepper.py
+++ b/pepper/libpepper.py
@@ -447,13 +447,14 @@ class Pepper(object):
         authentication token or an empty dict

         '''
+        variables = locals()
         kwargs.update(
             dict(
-                (key, locals()[key]) for key in (
+                (key, variables[key]) for key in (
                     'username',
                     'password',
                     'eauth'
-                ) if locals()[key] is not None
+                ) if variables[key] is not None
             )
         )
         self.auth = self._send_auth('/login', **kwargs).get('return', [{}])[0]
````
The problem seems to be that locals() is empty in the calling-context of the generator expression.

**Comment by vangourd** [comment]
That seems to have fixed it for me! Now on to resolving an SSL Problem.
