### ISSUE TITLE
client=runner commands are not working anymore 

### ISSUE THREAD

**Issue by PierreR** [saltstack/pepper#125]
I have just realized (two days after updating from 0.5.0 to 0.5.5 that my `client=runner` commands are not working anymore.

For instance:
```
$ pepper --client=runner manage.status -vvv
Error with request
Traceback (most recent call last):
  File "/nix/store/qpybjsymzrhm3vv8xvdblav3cr05y9h8-salt-pepper-0.5.5/lib/python2.7/site-packages/pepper/libpepper.py", line 235, in req
    f = urlopen(req)
  File "/nix/store/7b2z0vfbs9539ga4pxx5gmli47rz5y3n-python-2.7.14/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/nix/store/7b2z0vfbs9539ga4pxx5gmli47rz5y3n-python-2.7.14/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/nix/store/7b2z0vfbs9539ga4pxx5gmli47rz5y3n-python-2.7.14/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/nix/store/7b2z0vfbs9539ga4pxx5gmli47rz5y3n-python-2.7.14/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/nix/store/7b2z0vfbs9539ga4pxx5gmli47rz5y3n-python-2.7.14/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/nix/store/7b2z0vfbs9539ga4pxx5gmli47rz5y3n-python-2.7.14/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
DEBUG 2018-03-06 15:23:59,591 libpepper: Error with request
```
Same issue with other runner command such as `pepper --client=runner doc.execution`.

Any help appreciated ...

**Comment by PierreR** [comment]
I actually have a nasty error on the server so maybe this is related to my recent update from salt 2016.11.5 to salt 2016.11.9 : 

```
  File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 274, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 962, in mark_future
    data = self.serial.loads(msg[0])
  File "/usr/lib/python2.7/site-packages/salt/payload.py", line 137, in loads
    ret = msgpack.loads(msg, use_list=True, encoding=encoding)
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
ExtraData: npack(b) received extra data.
2018-03-06 20:54:59,283 [cherrypy.access.42378000][INFO    ][1499] 10.248.0.5 - - [06/Mar/2018:20:54:59] "POST / HTTP/1.1" 503 742 "" "Python-urllib/2.7"
```

**Comment by PierreR** [comment]
I have just tried the same curl command and the failure only happen in the one using `2016.11.9` and works fine with   `2016.11.5` :
```
curl -ssik https://salt.sta.srv.cirb.lan:8000/run  \
         -H 'content-type: application/json' -H 'Accept: application/x-yaml'  -d '[{
      "username": "xxx",
      "password": "xxxxxx",
      "eauth": "ldap",
      "client": "runner",
      "fun": "doc.execution"
     }]'
```
So this has nothing to do with `pepper`. I guess it is yet another regression ...

**Comment by PierreR** [comment]
Here is the bug: https://github.com/saltstack/salt/issues/45291
