### ISSUE TITLE
Pepper install fails with pip on SLES 12 SP3

### ISSUE THREAD

**Issue by randyesq** [saltstack/pepper#176]
```
# pip install pepper
Collecting pepper
  Downloading https://files.pythonhosted.org/packages/9e/b2/4f24903de795e172b65392b65fe29004595561e5027930818000212a9424/Pepper-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Q4j4Jx/pepper/setup.py", line 36
        download_url=f'https://github.com/devosoft/Pepper/archive/{versioneer.get_version()}.tar.gz',
                                                                                                   ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Q4j4Jx/pepper/
```
Pip versions:
```
# pip --version
pip 18.1 from /usr/lib/python2.7/site-packages/pip (python 2.7)
```
OS Info:
```
# cat /etc/os-release
NAME="SLES"
VERSION="12-SP3"
VERSION_ID="12.3"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP3"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp3"
```

**Comment by mattp-** [comment]
pepper is actually https://pypi.org/project/salt-pepper/ 'salt-pepper' on pypi. that is .. something else.

**Comment by randyesq** [comment]
My mistake, thanks for setting me straight.
