### ISSUE TITLE
Server error on jobs.lookup_jid with runner client

### ISSUE THREAD

**Issue by bbinet** [saltstack/pepper#208]
When I run a function asynchronously with `--client=local_async`, I can't get the result with `jobs.lookup_jid` runner because it generates a HTTP Error 500: Internal Server Error.

For example:

```
$ pepper --client=local_async test-mc-1 test.ping
jid:
    20200701073413349464
minions:
    - test-mc-1

$ pepper -vvv --client=runner jobs.lookup_jid jid=20200701073413349464
Error with request
Traceback (most recent call last):
  File "/home/bruno/.virtualenvs/pepper/lib/python3.7/site-packages/pepper/libpepper.py", line 231, in req
    f = urlopen(req)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
Pepper error: Server error.
```

FYI, the issue is the same with pepper v0.7.6 and develop branch and salt-master version 2019.2.4 (Fluorine).

Are you able to reproduce this issue ?

**Comment by bbinet** [comment]
Also I can't see any relevant issue in salt-master and salt-api logs.

**Comment by mattp-** [comment]
there seems to be an issue with kwarg to arg spec parsing in salt itself. in the interim you can change the jid= to just a [jid], I need to look into salt siide when/where this broke.

**Comment by bbinet** [comment]
Same issue:

```
$ pepper -vvv --client=runner jobs.lookup_jid 20200702070249988093
Error with request
Traceback (most recent call last):
  File "/home/bruno/.virtualenvs/pepper/lib/python3.7/site-packages/pepper/libpepper.py", line 231, in req
    f = urlopen(req)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
Pepper error: Server error.
```
