### ISSUE TITLE
pepper doesnt seem to like self signed certs created by following the api install documentation

### ISSUE THREAD

**Issue by eedgar** [saltstack/pepper#23]
http://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html

```python
eedgar@i7:~/git/salt-mgmt/pepper$ sudo python setup.py install
running install
running build
running build_py
running build_scripts
copying and adjusting scripts/pepper -> build/scripts-2.7
running install_lib
running install_scripts
copying build/scripts-2.7/pepper -> /usr/local/bin
changing mode of /usr/local/bin/pepper to 775
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/salt_pepper-0.0.0.egg-info
Writing /usr/local/lib/python2.7/dist-packages/salt_pepper-0.0.0.egg-info
eedgar@i7:~/git/salt-mgmt/pepper$ pepper '*' test.ping
Error with request: <urlopen error EOF occurred in violation of protocol (_ssl.c:581)>
ERROR 2015-04-01 22:37:59,175 libpepper: Error with request: <urlopen error EOF occurred in violation of protocol (_ssl.c:581)>
Uncaught Pepper error (increase verbosity for the full traceback).
eedgar@i7:~/git/salt-mgmt/pepper$ pepper '*' test.ping -vvv
Error with request
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pepper/libpepper.py", line 103, in req
    f = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1207, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1169, in do_open
    raise URLError(err)
URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:581)>
DEBUG 2015-04-01 22:38:02,285 libpepper: Error with request
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pepper/libpepper.py", line 103, in req
    f = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1207, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1169, in do_open
    raise URLError(err)
URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:581)>
Error with request: <urlopen error EOF occurred in violation of protocol (_ssl.c:581)>
ERROR 2015-04-01 22:38:02,286 libpepper: Error with request: <urlopen error EOF occurred in violation of protocol (_ssl.c:581)>
Uncaught Pepper error (increase verbosity for the full traceback).
Uncaught traceback:
Traceback (most recent call last):
  File "/usr/local/bin/pepper", line 268, in <module>
    exit_code, results = main()
  File "/usr/local/bin/pepper", line 236, in main
    auth = api.login(saltuser, saltpass, salteauth)
  File "/usr/local/lib/python2.7/dist-packages/pepper/libpepper.py", line 215, in login
    'eauth': eauth}).get('return', [{}])[0]
  File "/usr/local/lib/python2.7/dist-packages/pepper/libpepper.py", line 103, in req
    f = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1207, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1169, in do_open
    raise URLError(err)
URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:581)>
DEBUG 2015-04-01 22:38:02,286 pepper: Uncaught traceback:
Traceback (most recent call last):
  File "/usr/local/bin/pepper", line 268, in <module>
    exit_code, results = main()
  File "/usr/local/bin/pepper", line 236, in main
    auth = api.login(saltuser, saltpass, salteauth)
  File "/usr/local/lib/python2.7/dist-packages/pepper/libpepper.py", line 215, in login
    'eauth': eauth}).get('return', [{}])[0]
  File "/usr/local/lib/python2.7/dist-packages/pepper/libpepper.py", line 103, in req
    f = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1207, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1169, in do_open
    raise URLError(err)
URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:581)>
```

**Comment by whiteinge** [comment]
Thanks for filing this. SSL support in Python is kind of a mess right now. (We've been dealing with similar things in Salt core in the last month.)

Can you tell me the exact version of Python you're running?

**Comment by eedgar** [comment]
it was one of the 2014 versions.  I have abandoned working on this particular issue and moved on to other things.

**Comment by whiteinge** [comment]
I'll close this out then.
