### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by tucked** [saltstack/pepper#241]
https://github.com/saltstack/pepper/blob/8ab18e8fb81c275e19c1345146116cf14b9f1223/pepper/__init__.py#L4

`pkg_resources` is provided by `setuptools`, but `setuptools` is not listed in `install_requires` in `setup.py`.

That leads to this:
```
Traceback (most recent call last):
  File "/home/tucked/.local/bin/pepper", line 7, in <module>
    import pepper.script
  File "/home/tucked/.local/pipx/venvs/salt-pepper/lib/python3.12/site-packages/pepper/__init__.py", line 4, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by barneysowood** [comment]
Should be resolved by #236

**Comment by tucked** [comment]
Thanks @barneysowood! Can we get a release?
