### ISSUE TITLE
ImportError: No module named argparse

### ISSUE THREAD

**Issue by stardust85** [saltstack/pepper#50]
```
[xxx@vagrant vagrant]$ pepper '*' test.ping
Traceback (most recent call last):
  File "/usr/bin/pepper", line 9, in <module>
    load_entry_point('pepper==0.2', 'console_scripts', 'pepper')()
  File "/usr/lib/python2.6/site-packages/pepper.py", line 558, in main
    import argparse
ImportError: No module named argparse
[xxx@vagrant vagrant]$
```

On python 2.6 argparse isn't available, so we should depend on it. We should reference it in setup.py

**Comment by whiteinge** [comment]
Pepper does not use argparse. You may have the `pepper` package installed instead of the `salt-pepper` package.

**Comment by stardust85** [comment]
Exactly! You're right.

**Comment by whiteinge** [comment]
I like the easy ones!  :-)

**Comment by stardust85** [comment]
Bug resolved in 8 minutes, that's really amazing :) :
