### ISSUE TITLE
Traceback when target doesn't match any minion

### ISSUE THREAD

**Issue by stardust85** [saltstack/pepper#51]
```
[xxx@devbox211 pepper]$ pepper -vvvvv 'saltmaster.*' test.ping # this works
{
    "saltmaster.example.com": true
}
[xxx@devbox211 pepper]$ pepper -vvvvv 'saltmasterrrrrr.*' test.ping # this prints wrong error message
'jid'
Uncaught Pepper error (increase verbosity for the full traceback).
Uncaught traceback:
Traceback (most recent call last):
  File "/usr/bin/pepper", line 26, in <module>
    exit_code, results = cli.run()
  File "/usr/lib/python2.6/site-packages/pepper/cli.py", line 238, in run
    nodesJid = nodesJidRet['return'][0]['jid']
KeyError: 'jid'
DEBUG 2015-08-13 07:26:58,770 pepper: Uncaught traceback:
Traceback (most recent call last):
  File "/usr/bin/pepper", line 26, in <module>
    exit_code, results = cli.run()
  File "/usr/lib/python2.6/site-packages/pepper/cli.py", line 238, in run
    nodesJid = nodesJidRet['return'][0]['jid']
KeyError: 'jid'
[xxx@devbox211 pepper]$
```

**Comment by whiteinge** [comment]
I think this was resolved in yesterday's release. Can you confirm/refute?

https://github.com/saltstack/pepper/releases/tag/0.3.7

**Comment by stardust85** [comment]
Yes it was :)

**Comment by whiteinge** [comment]
:checkered_flag:
